# Jekyll Configuration
title: Cammisa Buerhaus Blog
description: Writing and reflections
baseurl: "/blog_public"
url: "https://cammisabuer.haus"
author: Cammisa Buerhaus

# Build settings
markdown: kramdown

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files
exclude:
  - .github
  - node_modules
  - vendor
